Bootstrap: docker
From: quay.io/biocontainers/augustus:3.5.0--pl5321hf46c7bb_1

%labels
    MAINTAINER icaoberg
    EMAIL icaoberg@psc.edu
    SUPPORT help@psc.edu
    REPOSITORY http://gitub.com/pscedu/singularity-augustus
    COPYRIGHT Copyright © 2021-2023 Pittsburgh Supercomputing Center. All Rights Reserved.    
    VERSION 3.5.0

%runscript
    augustus "$@"
